
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://keithmifsud.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:

# Google tracking id

google-tracking-id: "UA-81858075-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Keith Mifsud"
title: "Keith Mifsud - Software and Embedded Systems Engineer"
description: "Software and Embedded Systems Engineer. Loves coding, improving processes, automation and keeping lists. Deep Learning and Quantum Computing enthusiast."
keywords: "keith, mifsud, keith mifsud, solutions engineer, software, embedded systems"
favicon: "/img/favicon.ico"

################
# Header layout #
################

header-text: "Keith Mifsud"

black-favicon: False # "/img/black-lab-glass.ico"

# background-img: "../img/amstedam_by_night.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 500
lines: # You can add HTML Tags in the Text
  - text: "Hi, I'm Keith..."
  - text: "an independent software "
  - text: "and embedded systems engineer... "
  - text: "I enjoy coding, automation, strategies ..."
  - text: "and keeping lists ..."
  - text: ".. I'm an enthusiast of ..."
  - text: "Deep Learning and Quantum Computing."

me-img: "/img/blog-author.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#093E63"
apple-status-bar-style: "#093E63"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "keith-mifsud"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "mifsud dot k at gmail dot com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Enjoys coding, improving processes and keeping lists. Is also an enthusiast of Deep Learning and Quantum Computing"
author_blurb_image: "/img/blog-author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/mifsudKeith"
  - title: "twitter"
    url: "https://twitter.com/keithmifsud"
  - title: "github"
    url: "https://github.com/keithmifsud"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
#  - title: "rss"
#    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
#  About: 'about'
#  Blog: 'latest-post'
#  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
# - jemoji
