# Site settings
description: Software and Embedded Systems Engineer. Loves coding, improving processes, automation and keeping lists. Deep Learning and Quantum Computing enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://keith-mifsud.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

lang: "en"

# User settings
username: Keith Mifsud
user_description: Loves coding, improving processes, cooking and an enthusiast on Deep Learning and Quantum Computing.
user_title: Software and Embedded Systems Engineer.
email: mifsud.k@gmail.com
twitter_username: keithmifsud
github_username:  keithmifsud
gplus_username:   mifsud.k
disqus_username: disqus_aZaw6EGryB

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Topics
    url: /topics
  - title: Tags
    url: /tags
  - title: About Me
    url: /about



# exclude development, dev info and notes from building.
exclude: ['package.json', 'src', 'node_modules', '_notes']
